# ZSH Settings
HISTFILE=${HOME}/.histfile
HISTSIZE=1000
SAVEHIST=1000
export HISTFILE HISTSIZE SAVEHIST

# Global Settings
LANG=en_US.UTF-8
LC_COLLATE=C
LC_CTYPE=$LANG
PATH=${PATH}:${HOME}/bin
EDITOR='emacsclient -t'
ALTERNATE_EDITOR="emacs --daemon && ${EDITOR}"
PROMPT='%m%% '
GTK2_RC_FILES="${HOME}/.cache/wal"
export PATH EDITOR ALTERNATE_EDITOR PROMPT GTK2_RC_FILES

# exec startx
